### ISSUE TITLE
那个PI的值所有论文里都是个位数，用作者方法算出来是好几十，是什么原因呢

### ISSUE THREAD

**Issue by diwuqi** [RyanXingQL/Image-Quality-Assessment-Toolbox#2]

**Comment by diwuqi** [comment]
那个PI值在论文里都是个位数，为什么用作者的代码的算出来是几十，差距也太大了吧

**Comment by ryanxingql** [comment]
你好，
1、PI这个指标由NIQE和Ma两个指标组成。如果我没记错的话，NIQE模型是需要训练的。也就是说，NIQE模型的表现和训练数据集有关。因此，如果你的测试数据集和NIQE的训练数据集差异较大，数值范围肯定不同。
2、你可以尝试下PI官方repo提供的指标，或[PyIQA仓库](https://github.com/chaofengc/IQA-PyTorch)提供的PI指标，作为参考。

由于我的仓库太久没有维护了，还是建议你用更新的PyIQA仓库。谢谢关注！
